# Generated by Django 4.2.4 on 2023-08-13 16:10

from django.db import migrations, models
import vinventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('vinventory', '0002_alter_wine_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='date_received',
            field=models.DateField(blank=True, default=vinventory.models.default_date_received, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='date_to_drink_end',
            field=models.DateField(blank=True, default=vinventory.models.default_date_to_drink_end, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='date_to_drink_start',
            field=models.DateField(blank=True, default=vinventory.models.default_date_to_drink_start, null=True),
        ),
    ]
